### ISSUE TITLE
Implement secret sharing of Guardian secret keys

### ISSUE THREAD

**Issue by eb-concordium** [Concordium/concordium-governance-committee-voting#13]
**Task description**
Implement the secret sharing of the guardians' secret key.

**Comment by abizjak** [comment]
As far as I understand this is done, and has been for some time. Should the issue be closed then? @tschudid

**Comment by tschudid** [comment]
Yes, this has been completed with [PR #1](https://github.com/Concordium/electionguard-rust/pull/1) and [PR #6](https://github.com/Concordium/electionguard-rust/pull/6)
