### ISSUE TITLE
Don't show "Load more" button if the list of ballot submissions is empty

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-governance-committee-voting#36]
**Bug Description**
Load more button appears if the list is empty.

**Steps to Reproduce**
Open the list of ballot submissions while the list is empty.

**Expected Result**
Button "Load more" doesn't show up.

**Actual Result**
Button "Load more" shows up.

**Comment by soerenbf** [comment]
Cannot reproduce this issue.
