### ISSUE TITLE
[guardian app] Unique bundle ID per distribution

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-governance-committee-voting#45]
**Task description**
To ensure that user configuration and data storage for different contracts and networks do not override each other, the bundle ID of the final distribution needs to be unique for each network/contract combination.

It's possible to merge configurations using `yarn tauri build --config`. An idea could be to make a script to build the following:

```json
{
  "tauri": {
    "bundle": {"identifier": "com.concordium.guardian.<net>.<index>.<subindex>"}
  }
}
```

and then merge it with the global config.

**Comment by mh-concordium** [comment]
Test
