### ISSUE TITLE
[Election contract] change schema type of byte registrations to hex strings

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-governance-committee-voting#56]
**Description**
To improve the experience when submitting ballots through the voting app (and also view contract state for debugging), it would be useful to represent byte arrays registered in the contract as hex strings.

- [x] Ballot submissions
- [ ] Guardian public key registration
- [ ] Guardian encrypted shares registration
- [ ] Guardian decryption share registration
- [ ] Guardian decryption proof registration

**Comment by soerenbf** [comment]
Reopened this as only the ballot submission had the schema type added to represent the associated byte array as hex. The rest are not as critical, as users will not be exposed to them.

**Comment by abizjak** [comment]
I would argue we should just close this. I don't see any point in spending time on making something that is not exposed to users from one incomprehensible representation to another.
