### ISSUE TITLE
[coordinator tool] Encrypted ballots are not scaled as expected when voting for multiple candidates

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-governance-committee-voting#63]
**Bug Description**
If a voter with X weight votes for 3 candidates in an election, it seems that each candidate result is scaled with X instead of X/3.

**Steps to Reproduce**
- Set up an election
- In the voting phase of an election, submit a vote for multiple candidates from an eligible account
- Tally + decrypt (joint effort by coordinator + guardians

**Expected Result**
The result produced for each candidate is scaled by the voting power of the voter divided with the number of candidates selected in the ballot

**Actual Result**
The result produced for each candidate is scaled by the voting power of the voter

**Comment by abizjak** [comment]
If I understand your complaint correctly, I think this is the intended behaviour.

**Comment by soerenbf** [comment]
Seems to be a misunderstanding on my behalf.
