### ISSUE TITLE
GitHub action for Guardian app

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-governance-committee-voting#80]
Set up Github action that would build Guardian app for all supported distributions.

**Comment by abizjak** [comment]
This actually exists, but it builds unsigned binaries due to key management issues.

https://github.com/Concordium/concordium-governance-committee-voting/releases

**Comment by abizjak** [comment]
There is a draft release now. You can run it yourself from https://github.com/Concordium/concordium-governance-committee-voting/releases

**Comment by mh-concordium** [comment]
Great, I have missed that it is already there. I will try it, thanks.
